### ISSUE TITLE
Upload and download notifs.

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/comrades#14] opened 2018-06-30 20:47 UTC
Upload and download will have notifs with a loader and then a uploaded/downloaded notif. 
Clicking on the downloaded(notif) one will open the file.
Make sure u don't create any memory leaks by passing contexts.

**Comment by Rushi98** [comment] 2018-07-01 03:03
duplicate of #4

**Comment by aayushsingla** [comment] 2018-07-08 18:39
How is this duplicate of #4 ? and sometimes passing context is important. If you want to show notification it is important to pass context.

**Comment by hardik124** [comment] 2018-07-08 19:57
@tanmaydixit  . i highly doubt that passing context causes memory leaks. If in this case it is causing ( which can be shown by profiling ,i guess @aayushsingla  should make it a habit to put screenshot of profiler) , we can remedy that by making destroying context and running a garbage cleanup after that.

**Comment by aayushsingla** [comment] 2018-07-08 20:36
This feature will be discussed in future. @hardik124  thanks for clearing the doubt regarding passing context.

**Closed by aayushsingla** 2018-07-08 20:36 UTC
Labels: approved, enhancement

**Comment by Rushi98** [comment] 2018-07-09 05:01
Profiling is how I noticed the leak. Apart from that, I think we should keep various app components (like main ui, background services, long running tasks, notifs) independent from each other (i.e. one should not block other)
